import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "../lib/api";
export default function ArtistPage() {
  const { id } = useParams(); const [data, setData] = useState(null);
  useEffect(() => { api.get(`/explore/artists/${id}`).then((r) => setData(r.data)).catch(() => setData({ missing: true })); }, [id]);
  if (!data) return <div className="max-w-[1480px] mx-auto px-6 py-20 meta-ink">opening artist file…</div>;
  if (data.missing) return <div className="max-w-[1480px] mx-auto px-6 py-20 font-editorial text-2xl italic">this artist file is unavailable.</div>;
  const { artist, albums } = data;
  return <div className="max-w-[1480px] mx-auto px-6 py-12"><Link to="/explore" className="meta-ink underline underline-offset-4">back to explore</Link><div className="grid lg:grid-cols-12 gap-8 mt-6"><div className="lg:col-span-5 aspect-[4/5] bg-[var(--parchment-deep)] border-2 border-[var(--ink)] brutal-shadow overflow-hidden">{artist.portrait_url && <img src={artist.portrait_url} alt={`${artist.name} portrait`} className="w-full h-full object-cover" />}</div><div className="lg:col-span-7"><div className="meta-ink">artist file · {artist.scene} · {artist.era}</div><h1 className="font-display font-black text-6xl md:text-8xl tracking-tighter mt-2">{artist.name}</h1><p className="font-editorial italic text-2xl mt-5">{artist.tagline}</p><div className="editorial-prose mt-8 max-w-2xl"><p>{artist.bio || "A verified editorial profile is not yet available for this artist."}</p></div>{artist.wiki_url && <a href={artist.wiki_url} target="_blank" rel="noreferrer" className="meta-ink inline-block mt-3 underline underline-offset-4">read source profile</a>}</div></div><section className="mt-14"><div className="meta-ink">discography in this archive</div><h2 className="font-display font-black text-4xl tracking-tighter mt-1">the worlds.</h2><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5 mt-6">{albums.map((album) => <Link to={`/album/${album.id}`} key={album.id} className="brutal-card overflow-hidden"><div className="aspect-square bg-[var(--parchment-deep)]">{album.artwork_url && <img src={album.artwork_url} alt={`${album.title} cover`} className="w-full h-full object-cover" />}</div><div className="p-4"><div className="meta-ink">{album.year}</div><div className="font-display font-black text-2xl">{album.title}</div></div></Link>)}</div></section></div>;
}
