import { useEffect, useState } from "react";
import { api } from "../lib/api";
import { toast } from "sonner";

export default function ModerationDesk() {
  const [data, setData] = useState({ lore: [], theories: [], reports: [], connections: [] }); const [loading, setLoading] = useState(true);
  const load = () => Promise.all([api.get("/moderation/queue"), api.get("/reports"), api.get("/connections/submissions")]).then(([queue, reports, connections]) => setData({ lore: queue.data.lore, theories: queue.data.theories, reports: reports.data, connections: connections.data })).catch(() => toast.error("Could not open moderation desk")).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  const decide = async (type, id, status) => { try { await api.post(`/moderation/${type}/${id}`, { status }); toast.success("Decision saved"); load(); } catch { toast.error("Could not save decision"); } };
  const approveConnection = async (id) => { try { await api.post(`/connections/submissions/${id}/approve`); toast.success("Connection published"); load(); } catch { toast.error("Could not publish connection"); } };
  const resolveReport = async (id) => { try { await api.post(`/reports/${id}/resolve`); toast.success("Report resolved"); load(); } catch { toast.error("Could not resolve report"); } };
  if (loading) return <div className="max-w-[1480px] mx-auto px-6 py-20 meta-ink">opening moderation desk…</div>;
  const ContentCard = ({ item, type }) => <article className="brutal-card-static p-5"><div className="meta-ink">{type} · by {item.author}</div><h2 className="font-display font-bold text-xl mt-1">{item.title}</h2><p className="font-editorial italic mt-2">{item.excerpt || item.abstract}</p><div className="flex flex-wrap gap-2 mt-4"><button className="brutal-btn acid" onClick={() => decide(type === "lore" ? "lore" : "theory", item.id, "published")}>publish</button><button className="brutal-btn invert" onClick={() => decide(type === "lore" ? "lore" : "theory", item.id, "needs_revision")}>revision</button><button className="brutal-btn" onClick={() => decide(type === "lore" ? "lore" : "theory", item.id, "rejected")}>reject</button></div></article>;
  return <main className="max-w-[1480px] mx-auto px-6 py-12"><div className="meta-ink">admin · editorial operations</div><h1 className="font-display font-black text-5xl md:text-7xl tracking-tighter mt-1">moderation desk.</h1><section className="mt-10"><h2 className="font-display font-black text-3xl">pending writing</h2><div className="grid md:grid-cols-2 gap-5 mt-4">{[...data.lore.map((item) => ({ item, type: "lore" })), ...data.theories.map((item) => ({ item, type: "theory" }))].map(({ item, type }) => <ContentCard key={item.id} item={item} type={type} />)}{!data.lore.length && !data.theories.length && <p className="font-editorial italic text-xl">nothing waiting for editorial review.</p>}</div></section><section className="mt-12"><h2 className="font-display font-black text-3xl">connection proposals</h2><div className="grid md:grid-cols-2 gap-4 mt-4">{data.connections.map((item) => <article className="brutal-card-static p-5" key={item.id}><div className="meta-ink">{item.type}</div><div className="font-display font-bold mt-1">{item.source_id} → {item.target_id}</div><p className="font-editorial italic mt-2">{item.description}</p><button className="brutal-btn acid mt-4" onClick={() => approveConnection(item.id)}>publish connection</button></article>)}</div></section><section className="mt-12"><h2 className="font-display font-black text-3xl">open reports</h2><div className="space-y-3 mt-4">{data.reports.map((item) => <div className="brutal-card-static p-4" key={item.id}><div className="meta-ink">{item.target_type} · {item.target_id}</div><p className="font-editorial italic">{item.reason}</p><button className="tag-chip mt-3" onClick={() => resolveReport(item.id)}>mark resolved</button></div>)}{!data.reports.length && <p className="font-editorial italic text-xl">no open reports.</p>}</div></section></main>;
}
